# Generated by Django 4.2.2 on 2023-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(max_length=60, verbose_name='Slug')),
                ('created_at', models.DateField(verbose_name='Date of creation')),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Main Image')),
                ('sub_image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Subsidiary Image')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['created_at'],
            },
        ),
    ]
