# Generated by Django 4.2.2 on 2023-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Slug'),
        ),
    ]
